### ISSUE TITLE
Use [package] name instead of [lib] name

### ISSUE THREAD

**Issue by althonos** [PyO3/pyo3-pack#1]
First of all: awesome project !

Now, here's the mostly subjective part: like `crates.io`, `pypi` does not have a strong policy on module naming, but the strong consensus is to use kebab case instead of underscore case. [There are 3x more packages with kebab case than with underscore case](https://gist.github.com/gene1wood/9472a9d0dffce1a56d6e796afc6539b8). 

Using the name in `[lib]` will enforce underscore case, since they must be a valid *crate* identifier, whereas using the name in `[package]` allows the package developer to choose whatever case he wants.

**Comment by konstin** [comment]
Thank you for the analysis! I've changed it so that the name of wheel/package will be the name in the `[package]` section and the name of the module/library is the name in the `[lib]` section, with a fallback the package name if there is no name in the lib section.

**Comment by rth** [comment]
I have a package name with a dash in the `[package]` section of `Cargo.toml`, however generated wheels have underscores instead of dashes in their names. I thought this shouldn't have happened after this issue was resolved, or am I missing something? Is there a way around it? 

Using rustc 1.32.0-nightly (6f93e93af 2018-11-14) and pyo3-pack 0.4.0.
