### ISSUE TITLE
Clarification on the manylinux wheels comliance

### ISSUE THREAD

**Issue by rth** [PyO3/pyo3-pack#47]
Thanks for this very useful package!

Regarding building manylinux1 wheels, the readme states,

> The pypa offers a special docker container and a tool called auditwheel to ensure compliance with the manylinux rules. pyo3-pack contains a reimplementation of the most important part of auditwheel that checks the generated library, so there's no need to use external tools. If you want to disable the manylinux compliance checks for some reason, use the --skip-auditwheel flag.

As far as I understand, another requirement of the [manylinux policy](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy) is that it needs to work with  CentOS 5.11 (on which those docker images are based). Does it mean that one has to use these docker images (and install rust nightly there)? The readme sounds like it's not necessary...

**Comment by konstin** [comment]
In theory, rust should only link symbols old enough for manylinux compliance. iirc in there's a bug where rust currently links two more recent symbols, breaking manylinux and even manylinux2010 compliance. Unfortunately I currently can't check because the latest nightly crashes in the manylinux container with some error about the gcc version: https://github.com/rust-lang/rust/issues/56849. So this means you currently need the docker container for full compliance; I had started creating a (Dockerfile)[https://github.com/PyO3/pyo3-pack/blob/master/Dockerfile] with all tools installed, but not finished it.

**Comment by rth** [comment]
Thanks for the explanations @konstin !

**Comment by konstin** [comment]
I've filed https://github.com/rust-lang/rust/issues/57497 for glibc part, but I'm not sure if that will get fixed. I've also created a docker container based on the manylinux container with all required tools installed and published it under [konstin2/pyo3-pack](https://cloud.docker.com/repository/docker/konstin2/pyo3-pack), but I think I need to pin the nightly, I don't know yet if tags get published and the upload feature can't be used (reqwest got rustls support just 3 days ago, maybe that could help, but that needs to be manually tested for regressions).

**Comment by konstin** [comment]
I've improved the Dockerfile a good bit and updated with proper information.

@rth Could have a look at the readme please and tell me if that fixes the issue?

**Comment by rth** [comment]
yes https://github.com/PyO3/pyo3-pack/commit/537527187b914344ebaf9ac3264f5a6b96b0412d fixes this issue, thanks @konstin !

**Comment by ijl** [comment]
@konstin should konstin2/pyo3-pack be public? I need to login to access it.

**Comment by konstin** [comment]
Thanks for the note @ijl, I've changed it to the correct link.
