### ISSUE TITLE
Support non-manylinux Linux builds

### ISSUE THREAD

**Issue by ijl** [PyO3/pyo3-pack#51]
Linux builds should be able to target their specific installation rather than the manylinux1 target. Maybe a flag of `--env-specific` or something better named, which implies `--skip-auditwheel`, and generates the `...-cp37-cp37m-linux_x86_64.whl` tag?

**Comment by konstin** [comment]
What is the usecase / advantage of having `linux_x86_64` instead of `manylinux1` builds?

**Comment by ijl** [comment]
If I build on an up to date Linux machine, apparently it breaks manylinux1 by linking a more recent glibc. It's also not unusual to vendor wheels for a project, where you may want to commit extensions compiled against your specific distro. It seems simpler and consistent wheel's manylinux1 being a subset of platform-specific wheels to just let platform-specific wheels be built on Linux.

**Comment by konstin** [comment]
Those sound like good reasons to support the non-manylinux tag. For the implementation I currently favour a `--manylinux=[on|skip-auditwheel|off]` option that deprecates the current `--skip-auditwheel`.

You can't build cpython libraries on alpine, because python itself uses glibc and so all extension modules need to use it, too. For pyo3-pack and other binaries this restriction does not apply because they don't need to be loaded by cpython.
